Repository goby-lang/goby, pull requests merged in 2018-09, with the labels that each got.

#739 Unify error messages in string.go
  native/plugin/plugin.go
  native/result/bindings.go
  vm/errors/error.go
  vm/string.go
  vm/string_test.go
Labels: Refactoring, in progress

#734 Add API docs to class.go
  vm/class.go
Labels: Documentation, in progress

#740 Update test matcher's names
  compiler/ast/testable_expressions.go
  compiler/ast/testable_statements.go
  compiler/parser/expression_parsing_test.go
  compiler/parser/method_definition_parsing_test.go
  compiler/parser/parser_test.go
  compiler/parser/statement_parsing_test.go
Labels: Refactoring, in progress

#738 Unify error message range
  vm/range.go
  vm/range_test.go
Labels: Refactoring, in progress

#745 Apply go fmt
  compiler/bytecode/instruction.go
  native/ripper/ripper.go
  native/ripper/ripper_test.go
  vm/array_test.go
  vm/channel.go
  vm/concurrent_array.go
  vm/concurrent_hash.go
  vm/concurrent_rw_lock.go
  vm/go_map.go
  vm/go_map_test.go
  vm/hash.go
  vm/hash_test.go
  vm/http.go
  vm/json_test.go
  vm/match_data.go
  vm/match_data_test.go
  vm/null.go
  vm/regexp_test.go
Labels: Refactoring, in progress

#735 Update error messages in json.go
  vm/json.go
  vm/json_test.go
Labels: Refactoring, in progress

#741 vm: use type switch var binding to avoid redundant type assertions
  vm/array.go
  vm/integer.go
  vm/string.go
Labels: Refactoring

#744 vm,cmd/binder,igb,compiler/parser: simplify `x = x <op> y` to `x <op> = y`
  cmd/binder/main.go
  compiler/parser/method_call_parsing.go
  compiler/parser/statement_parsing.go
  igb/repl.go
  vm/class.go
  vm/thread.go
Labels: Refactoring, in progress

#743 vm: remove unnecessary lambda wrappers
  vm/float.go
  vm/integer.go
Labels: Refactoring, in progress

#746 Add Array#index_with
  vm/array.go
  vm/array_test.go
Labels: Priority Medium, enhancement, in progress

#737 Unify error messages hash
  vm/array.go
  vm/errors/error.go
  vm/go_object.go
  vm/hash.go
  vm/hash_test.go
Labels: Refactoring, in progress

#736 Fix error message in integer.go
  vm/integer.go
  vm/integer_test.go
Labels: Refactoring, in progress
