Repository goby-lang/goby, pull requests merged in 2018-08, with the labels that each got.

#712 Unify to PositiveValue error message
  vm/array.go
  vm/array_test.go
  vm/concurrent_array_test.go
  vm/errors/error.go
Labels: Refactoring, in progress

#711 Unify to WrongArgumentTypeFormat
  vm/class.go
  vm/class_test.go
Labels: Refactoring, in progress

#710 Unify to CantYieldWithoutBlockFormat
  vm/instruction.go
Labels: Refactoring, in progress

#708 Remove unnecessary conversions on instructions
  compiler/bytecode/expression_generation.go
  compiler/bytecode/expression_generation_test.go
  compiler/bytecode/generator.go
  compiler/bytecode/generator_test.go
  compiler/bytecode/instruction.go
  compiler/bytecode/statement_generation.go
  compiler/bytecode/statement_generation_test.go
  compiler/compiler.go
  native/db/db.go
  native/ripper/ripper.go
  native/ripper/ripper_test.go
  vm/array_enumerator_test.go
  vm/benchmark_test.go
  vm/call_object.go
  vm/inspection_methods.go
  vm/instruction.go
  vm/instruction_translator.go
  vm/method.go
  vm/object.go
  vm/thread.go
Labels: Performance, VM, enhancement, reviewing

#705 Use a simpler concurrency benchmark script.
  vm/benchmark_test.go
Labels: Benchmark, help wanted, in progress

#704 Implement Array#sort
  vm/array.go
  vm/array_test.go
  vm/float.go
  vm/hash_test.go
  vm/integer.go
  vm/numeric.go
Labels: Feature, VM, reviewing

#718 bugfix: allow more than 5 local variables
  vm/call_frame.go
  vm/vm_test.go
Labels: Priority High, VM, bug

#720 Add --profile-mem flag and rename -p to --profile-cpu
  goby.go
  goby_test.go
Labels: Command line, in progress

#724 Fixes by go vet checks
  vm/concurrent_hash.go
  vm/concurrent_rw_lock.go
  vm/error.go
  vm/issue_vm.go
  vm/thread.go
Labels: bug, in progress

#729 Fix #726: float `0.0` should not be truncated to `0`
  vm/decimal.go
  vm/decimal_test.go
  vm/float.go
  vm/float_test.go
Labels: Testing, VM, in progress
