Repository goby-lang/goby, pull requests merged in 2018-07, with the labels that each got.

#694 Add print()
  vm/class.go
Labels: Feature

#696 NullObject now converts to a blank string in all the cases
  vm/array_test.go
  vm/concurrent_array_test.go
  vm/null.go
  vm/null_test.go
Labels: bug, in progress

#691 Reduce method call memory allocation
  native/db/db.go
  travis.sh
  vm/array.go
  vm/block.go
  vm/boolean.go
  vm/call_frame.go
  vm/call_object.go
  vm/channel.go
  vm/class.go
  vm/concurrent_array.go
  vm/concurrent_hash.go
  vm/concurrent_rw_lock.go
  vm/decimal.go
  vm/error_test.go
  vm/file.go
  vm/float.go
  vm/go_map.go
  vm/go_object.go
  vm/hash.go
  vm/http.go
  vm/http_client.go
  vm/instruction.go
  vm/integer.go
  vm/json.go
  vm/match_data.go
  vm/method.go
  vm/null.go
  vm/object.go
  vm/plugin.go
  vm/plugin_integration_test.go
  vm/range.go
  vm/regexp.go
  vm/simple_server.go
  vm/string.go
  vm/thread.go
  vm/uri.go
  vm/vm.go
Labels: Performance, Priority High, Refactoring, VM, in progress

#699 Fix plugin's travis failure
  .gitignore
  vm/plugin_integration_test.go
Labels: in progress

#701 Binder
  Gopkg.lock
  Gopkg.toml
  cmd/binder/Readme.md
  cmd/binder/main.go
  goby.go
  lib/result.gb
  native/result/bindings.go
  native/result/result.go
  specs/result_spec.gb
  vendor/github.com/dave/jennifer/LICENSE
  vendor/github.com/dave/jennifer/jen/add.go
  vendor/github.com/dave/jennifer/jen/comments.go
  vendor/github.com/dave/jennifer/jen/custom.go
  vendor/github.com/dave/jennifer/jen/dict.go
  vendor/github.com/dave/jennifer/jen/do.go
  vendor/github.com/dave/jennifer/jen/file.go
  vendor/github.com/dave/jennifer/jen/generated.go
  vendor/github.com/dave/jennifer/jen/group.go
  vendor/github.com/dave/jennifer/jen/hints.go
  vendor/github.com/dave/jennifer/jen/jen.go
  vendor/github.com/dave/jennifer/jen/lit.go
  vendor/github.com/dave/jennifer/jen/statement.go
  vendor/github.com/dave/jennifer/jen/tag.go
  vendor/github.com/dave/jennifer/jen/tokens.go
  vendor/github.com/fatih/camelcase/.travis.yml
  vendor/github.com/fatih/camelcase/LICENSE.md
  vendor/github.com/fatih/camelcase/README.md
  vendor/github.com/fatih/camelcase/camelcase.go
  vm/channel.go
  vm/class.go
  vm/thread.go
  vm/vm.go
Labels: Feature, reviewing

#692 Add thread benchmark.
  vm/benchmark_test.go
Labels: Benchmark, in progress

#703 Fix typos in binder/Readme
  cmd/binder/Readme.md
Labels: Documentation, in progress

#658 Add Ripper class
  compiler/token/token.go
  goby.go
  lib/ripper.gb
  native/result/result.go
  native/ripper/ripper.go
  native/ripper/ripper_test.go
  vm/array.go
  vm/boolean.go
  vm/class.go
  vm/classes/classes.go
  vm/decimal.go
  vm/error.go
  vm/float.go
  vm/hash.go
  vm/integer.go
  vm/match_data.go
  vm/null.go
  vm/range.go
  vm/string.go
Labels: Feature, Library, in progress

#707 Fix apidoc in Ripper#instruction
  native/ripper/ripper.go
Labels: in progress

#706 Improve error handling
  vm/repl.go
  vm/thread.go
  vm/vm.go
Labels: Priority High, Refactoring, VM, in progress
