Repository goby-lang/goby, pull requests merged in 2018-06, with the labels that each got.

#676 Add Class#inherits_method_missing
  vm/class.go
  vm/class_test.go
  vm/evaluation_test.go
  vm/instruction.go
  vm/object.go
Labels: Priority High, VM, feature, in progress

#681 Prohibit module initialization
  vm/array.go
  vm/block.go
  vm/boolean.go
  vm/channel.go
  vm/class.go
  vm/class_test.go
  vm/classes/classes.go
  vm/concurrent_array.go
  vm/concurrent_hash.go
  vm/concurrent_rw_lock.go
  vm/decimal.go
  vm/error.go
  vm/file.go
  vm/float.go
  vm/go_map.go
  vm/go_object.go
  vm/hash.go
  vm/http.go
  vm/http_client.go
  vm/instruction.go
  vm/integer.go
  vm/json.go
  vm/match_data.go
  vm/method.go
  vm/null.go
  vm/plugin.go
  vm/range.go
  vm/regexp.go
  vm/simple_server.go
  vm/string.go
  vm/uri.go
  vm/vm.go
Labels: Priority High, VM, in progress

#682 Move current roadmap on README to wiki for easier update
  README.md
Labels: Documentation, in progress

#684 Export InitStringObject function
  vm/array.go
  vm/class.go
  vm/concurrent_hash.go
  vm/decimal.go
  vm/file.go
  vm/hash.go
  vm/http.go
  vm/http_client.go
  vm/instruction.go
  vm/integer.go
  vm/match_data.go
  vm/null.go
  vm/range.go
  vm/simple_server.go
  vm/string.go
  vm/uri.go
  vm/vm.go
Labels: VM, reviewing

#688 Use dep instead of godep
  Godeps/Godeps.json
  Godeps/Readme
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/dlclark/regexp2/syntax/charclass.go
  vendor/github.com/lib/pq/notify.go
  vendor/golang.org/x/sys/unix/syscall.go
Labels: Refactoring, in progress

#689 Update Dockerfile to use dep for installing dependencies.
  Dockerfile
Labels: Priority High, in progress

#686 Add Class.constants method.
  vm/class.go
  vm/class_test.go
Labels: Priority High, VM, feature, in progress
