Repository goby-lang/goby, pull requests merged in 2018-02, with the labels that each got.

#587 Implement #550
  .travis.yml
  Makefile
  compiler/ast/common_test_helpers.go
  compiler/ast/expressions.go
  compiler/ast/expressions_test_helpers.go
  compiler/ast/statements.go
  compiler/ast/statements_test_helpers.go
  compiler/ast/testable_expressions.go
  compiler/ast/testable_statements.go
  compiler/parser/expression_parsing_test.go
  compiler/parser/method_definition_parsing_test.go
  compiler/parser/parser_test.go
  compiler/parser/statement_parsing_test.go
  travis.sh
Labels: Needs feedback, Parser, Priority High, in progress, testing

#597 Go 1.10
  .travis.yml
  Dockerfile
  compiler/ast/common_test_helpers.go
  goby.go
  vm/block.go
  vm/decimal_test.go
  vm/http_client_test.go
  vm/http_test.go
  vm/instruction.go
  vm/issue_vm.go
  vm/vm_test.go
Labels: Priority High, reviewing

#527 Added tests for goby command
  .gitignore
  goby_test.go
Labels: in progress

#600 Support string range indexing
  vm/decimal_test.go
  vm/hash.go
  vm/string.go
  vm/string_test.go
  vm/thread.go
  vm/vm_test.go
Labels: Priority High, VM, feature, reviewing

#598 Implement #590
  compiler/ast/expressions_test_helpers.go
  compiler/ast/statements_test_helpers.go
  compiler/ast/testable_expressions.go
  compiler/ast/testable_statements.go
  compiler/parser/expression_parsing_test.go
  vm/error_test.go
  vm/vm_test.go
Labels: enhancement, reviewing, testing

#599 Fix #589
  vm/class.go
  vm/class_test.go
Labels: in progress

#601 Show lib file name if any error occurs when loading it.
  vm/thread.go
  vm/vm.go
Labels: Priority High, VM, feature, in progress, reviewing

#604 Implement #602 and fix simple server
  vm/call_frame.go
  vm/instruction.go
  vm/simple_server.go
  vm/simple_server_test.go
Labels: Priority High, VM, in progress, testing

#607 Implement #606
  samples/to_json.gb
  vm/array.go
  vm/block.go
  vm/boolean.go
  vm/channel.go
  vm/class.go
  vm/concurrent_array.go
  vm/concurrent_hash.go
  vm/concurrent_rw_lock.go
  vm/decimal.go
  vm/error.go
  vm/file.go
  vm/float.go
  vm/go_map.go
  vm/go_object.go
  vm/hash.go
  vm/hash_test.go
  vm/integer.go
  vm/match_data.go
  vm/method.go
  vm/null.go
  vm/object.go
  vm/plugin.go
  vm/range.go
  vm/regexp.go
  vm/string.go
Labels: Priority High, VM, feature, in progress
