Repository goby-lang/goby, pull requests merged in 2018-04, with the labels that each got.

#639 Fix #636
  vm/class.go
  vm/class_test.go
  vm/range.go
  vm/spec.go
  vm/spec_test.go
Labels: Priority High, VM, in progress

#641 Add Syntax highlighting section to README
  README.md
Labels: Documentation, in progress

#646 Make lib path customizable on build, using the env variable GOBY_LIBPATH
  Makefile
  vm/thread.go
  vm/vm.go
Labels: in progress

#645 Fix panic When a library file is not found on startup
  vm/thread.go
  vm/vm_test.go
Labels: in progress

#651 Feature: Class#respond_to?
  vm/class.go
  vm/class_test.go
Labels: in progress

#649 Add Integer#to_d
  vm/integer.go
  vm/integer_test.go
Labels: in progress

#652 Feature/issue 643
  compiler/parser/statement_parsing.go
  compiler/parser/statement_parsing_test.go
  igb/repl.go
Labels: Parser, Priority High, REPL, in progress

#659 rework benchmark running
  Makefile
  benchmark.rb
  current_benchmarks
Labels: enhancement, in progress
