Repository goby-lang/goby, pull requests merged in 2018-05, with the labels that each got.

#661 Fix an apidoc bug in array.go
  vm/array.go
Labels: in progress

#665 Update apidoc and tests in array.go
  vm/array.go
  vm/array_test.go
Labels: Documentation, in progress

#667 Add api-doc and tests to block.go
  vm/block.go
  vm/block_test.go
Labels: Documentation, in progress, testing

#668 Fix array's methods
  vm/array.go
  vm/array_test.go
Labels: in progress

#669 Update api-doc in boolean.go
  vm/boolean.go
  vm/class.go
  vm/evaluation_test.go
Labels: in progress

#670 Update api-doc for channel.go
  vm/channel.go
  vm/channel_and_thread_test.go
Labels: Documentation, in progress

#672 Support method missing
  vm/evaluation_test.go
  vm/instruction.go
  vm/object.go
Labels: Priority High, VM, feature, in progress

#675 Add Option class
  .gitignore
  lib/result.gb
  specs/result_spec.gb
  vm/class.go
Labels: in progress
