Repository goby-lang/goby, pull requests merged in 2018-03, with the labels that each got.

#603 Fix #444
  compiler/parser/expression_parsing.go
  compiler/parser/expression_parsing_test.go
Labels: in progress

#608 Fix #529
  vm/vm_test.go
Labels: in progress

#563 Fix #540
  vm/array.go
  vm/array_test.go
  vm/hash.go
  vm/hash_test.go
  vm/range.go
  vm/range_test.go
  vm/string.go
  vm/string_test.go
  vm/thread.go
Labels: in progress

#613 Fix a typo
  vm/classes/classes.go
Labels: in progress

#614 Implement Module{#>=, #<, #<=} as Module#>
  vm/class.go
  vm/class_test.go
Labels: VM, feature, in progress

#618 Implement instance_eval
  vm/class.go
  vm/class_test.go
Labels: Priority High, VM, feature, in progress

#621 Fix issues for running sample app
  compiler/bytecode/statement_generation.go
  vm/evaluation_test.go
  vm/thread.go
Labels: Priority High, VM, in progress

#622 Implement exit() as kernel method
  igb/repl.go
  vm/class.go
  vm/class_test.go
Labels: VM, in progress

#625 Add exit status to Spec.test invocations
  lib/spec.gb
Labels: reviewing, testing

#626 Test framework: add #not_to relation
  lib/spec.gb
  specs/array_spec.gb
  specs/spec_spec.gb
Labels: Library, enhancement, in progress, testing

#627 Make thread (not vm)'s error handling more robust.
  vm/thread.go
Labels: Priority High, VM, in progress

#619 Implement test framework
  lib/spec.gb
  specs/spec_spec.gb
  travis.sh
  vm/spec.go
  vm/spec_test.go
  vm/thread.go
  vm/vm.go
Labels: enhancement, feature, in progress

#623 feature/issue-574
  compiler/parser/parser.go
  compiler/parser/parser_test.go
  compiler/parser/statement_parsing.go
  compiler/parser/statement_parsing_test.go
Labels: in progress

#632 Refactor builtin spec functionality's implementation
  goby.go
  goby_test.go
  lib/spec.gb
  vm/spec_test.go
Labels: Library, Refactoring, in progress

#633 Feature/issue 624
  compiler/parser/parser.go
  compiler/parser/statement_parsing.go
  compiler/parser/statement_parsing_test.go
  vm/error_test.go
Labels: in progress

#617 Descending range
  lib/range_enumerator.gb
  vm/range.go
  vm/range_enumerator_test.go
  vm/range_test.go
Labels: in progress

#638 Feature/issue 524
  compiler/parser/expression_parsing_test.go
  compiler/parser/parser.go
Labels: in progress
