Repository goby-lang/goby, pull requests merged in 2018-11, with the labels that each got.

#752 Update Dockerfile for Go 1.11
  Dockerfile
Labels: in progress

#749 Bump Go versions and use '.x' to always get latest patch versions
  .travis.yml
Labels: in progress

#747 Retry remove-builtin-method-function branch #719
  vm/array.go
  vm/block.go
  vm/boolean.go
  vm/channel.go
  vm/class.go
  vm/concurrent_array.go
  vm/concurrent_hash.go
  vm/concurrent_rw_lock.go
  vm/decimal.go
  vm/file.go
  vm/float.go
  vm/go_map.go
  vm/go_object.go
  vm/hash.go
  vm/http.go
  vm/integer.go
  vm/json.go
  vm/match_data.go
  vm/null.go
  vm/range.go
  vm/regexp.go
  vm/string.go
  vm/uri.go
Labels: Refactoring, in progress

#757 Remove redundant copy
  vm/call_frame.go
Labels: Refactoring, VM, in progress
