Repository goby-lang/goby, pull requests merged in 2019-09, with the labels that each got.

#778 Temporarily remove race condition check for tests
  travis.sh
Labels: Testing

#777 Add Go 1.13.x to .travis.yml
  .travis.yml
Labels: enhancement

#779 Add desc for using goby in spacevim
  README.md
Labels: Documentation

#780 Update slack self-invite service's url
  README.md
Labels: Documentation

#782 Improve the output of `Object#inspect`
  vm/class_test.go
  vm/concurrent_rw_lock.go
  vm/error_test.go
  vm/evaluation_test.go
  vm/hash_test.go
  vm/object.go
  vm/validate.go
Labels: enhancement

#786 Return error when found invalid assignment value (currently ignore)
  compiler/ast/expressions.go
  compiler/parser/expression_parsing.go
  compiler/parser/expression_parsing_test.go
Labels: Parser, bug
