Repository goby-lang/goby, pull requests merged in 2019-10, with the labels that each got.

#788 Implement Object#tap
  vm/class.go
  vm/object_test.go
Labels: Feature, VM

#791 Implement dup
  vm/array.go
  vm/array_test.go
  vm/boolean_test.go
  vm/class.go
  vm/decimal_test.go
  vm/environment.go
  vm/error.go
  vm/errors/error.go
  vm/float_test.go
  vm/hash.go
  vm/hash_test.go
  vm/integer_test.go
  vm/object.go
  vm/object_test.go
  vm/range_test.go
  vm/regexp_test.go
  vm/string.go
  vm/string_test.go
Labels: Feature, VM

#793 [Refactor] Use Token Factory Method
  compiler/lexer/lexer.go
  compiler/parser/expression_parsing.go
  compiler/token/token.go
  compiler/token/token_test.go
Labels: Lexer, Refactoring

#795 Use equalTo() as a interface for equality comparison
  vm/array.go
  vm/array_test.go
  vm/boolean.go
  vm/boolean_test.go
  vm/call_object.go
  vm/class.go
  vm/concurrent_array.go
  vm/decimal.go
  vm/float.go
  vm/hash.go
  vm/hash_test.go
  vm/integer.go
  vm/integer_test.go
  vm/null.go
  vm/object.go
  vm/object_test.go
  vm/range.go
  vm/regexp.go
  vm/regexp_test.go
  vm/string.go
  vm/string_test.go
Labels: Refactoring, VM, enhancement

#796 Fix object_id method
  native/plugin/plugin.go
  native/result/result.go
  vm/array.go
  vm/block.go
  vm/boolean.go
  vm/channel.go
  vm/class.go
  vm/concurrent_array.go
  vm/concurrent_hash.go
  vm/concurrent_rw_lock.go
  vm/decimal.go
  vm/error.go
  vm/file.go
  vm/float.go
  vm/go_map.go
  vm/go_object.go
  vm/hash.go
  vm/instruction.go
  vm/integer.go
  vm/match_data.go
  vm/null.go
  vm/object.go
  vm/object_test.go
  vm/range.go
  vm/regexp.go
  vm/string.go
Labels: Priority High, Refactoring, VM, bug, enhancement

#798 Split lexer tests into smaller pieces
  compiler/lexer/lexer_test.go
Labels: Lexer, Refactoring

#683 Fix #555
  compiler/bytecode/expression_generation.go
  compiler/parser/expression_parsing_test.go
  compiler/parser/parser.go
  vm/evaluation_test.go
Labels: CodeGenerator, Parser, bug
