Repository goby-lang/goby, pull requests merged in 2019-12, with the labels that each got.

#807 Perform gofmt -w
  vm/object_test.go
Labels: Refactoring

#811 Fix #809
  goby_test.go
  test_fixtures/file_with_error.gb
  vm/thread.go
  vm/vm.go
Labels: Priority High, bug, enhancement

#806 Fix by ineffassign
  goby.go
  goby_test.go
  vm/channel.go
  vm/class.go
  vm/http.go
  vm/stack.go
Labels: Goby.go, VM

#805 Fix misspells
  vm/class.go
Labels: Documentation

#812 Fix by golint on test_fixtures
  test_fixtures/import_test/plugin/lib/lib.go
  test_fixtures/import_test/plugin/plugin.go
  test_fixtures/import_test/struct/struct.go
Labels: Documentation, Priority Low

#813 Fix by golint on cmd/binder
  cmd/binder/main.go
Labels: Documentation, Priority Low

#814 Fix by golint on native/
  native/db/db.go
  native/plugin/plugin.go
  native/ripper/ripper.go
Labels: Documentation, Priority Low

#818 Remove unnecessary findIndex()
  compiler/bytecode/instruction.go
Labels: Refactoring

#817 Fix by golint on compiler/bytecode
  compiler/bytecode/instruction.go
Labels: Documentation, Priority Low

#816 Fix by golint on compiler/ast
  compiler/ast/ast.go
  compiler/ast/expressions.go
  compiler/ast/expressions_test_helpers.go
  compiler/ast/statements.go
  compiler/ast/statements_test_helpers.go
  compiler/ast/testable_expressions.go
  compiler/ast/testable_statements.go
  compiler/ast/variables.go
Labels: Documentation, Priority Low

#815 Fix by golint
  goby.go
Labels: Documentation, Goby.go, Priority Low
