Repository goby-lang/goby, pull requests merged in 2020-03, with the labels that each got.

#832 Support Array.new(args)
  vm/array.go
  vm/array_test.go
  vm/error_test.go
Labels: Feature, VM

#802 Tadpole operator to `String#match?`
  compiler/lexer/lexer.go
  compiler/lexer/lexer_test.go
  compiler/parser/parser.go
  compiler/parser/precedence/precedence.go
  compiler/token/token.go
  compiler/token/token_test.go
  native/ripper/ripper.go
  vm/string.go
  vm/string_test.go
Labels: Feature, Priority Low

#836 Fix method call & error message handling
  vm/array.go
  vm/array_enumerator_test.go
  vm/class.go
  vm/class_test.go
  vm/error_test.go
  vm/instruction.go
  vm/range_enumerator_test.go
  vm/regexp.go
  vm/thread.go
  vm/vm_test.go
Labels: Refactoring, VM, bug fix

#835 Extend Spec lib with after/before callback support
  codecov.yml
  lib/spec.gb
  specs/spec_spec.gb
Labels: Library, Testing

#833 Document Goby's error handling
  compiler/compiler.go
  compiler/parser/parser.go
  vm/thread.go
  vm/vm.go
Labels: Documentation, VM

#819 Add random number generation by mapping rand() to math/rand
  vm/class.go
  vm/class_test.go
Labels: Feature, VM

#837 Fix #584
  vm/thread.go
  vm/vm_test.go
Labels: VM, bug fix
