Repository goby-lang/goby, pull requests merged in 2020-10, with the labels that each got.

#861 Update to go 1.15
  .travis.yml
  README.md
Labels: Priority Low

#862 Add URI.parse argument check
  vm/uri.go
  vm/uri_test.go
Labels: bug fix

#863 Add fragment on URI
  vm/uri.go
  vm/uri_test.go
Labels: Feature

#865 Add Net::HTTP methods check
  vm/http.go
  vm/http_test.go
Labels: VM, bug fix
